apiVersion: v1
kind: PersistentVolume
metadata:
  name: trustyai-service-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trustyai-service-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi